version: "3.8"
services:
  beeja-service-registry:
    build: ./beeja-service-registry
    ports:
      - "8761:8761"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
  beeja-cloud-gateway:
    build: ./beeja-cloud-gateway
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    ports:
      - "8000:8000"
    depends_on:
      - beeja-service-registry
      - beeja-db-1
  beeja-accounts:
    build: ./beeja-accounts
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    ports:
      - "8080:8080"
    depends_on:
      - beeja-service-registry
      - beeja-cloud-gateway
      - beeja-db-1
  beeja-employee-management:
    build: ./beeja-employee-management
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    ports:
      - "8089:8089"
    depends_on:
      - beeja-service-registry
      - beeja-cloud-gateway
      - beeja-db-1
  beeja-expense:
    build: ./beeja-expense
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    ports:
      - "8091:8091"
    depends_on:
      - beeja-service-registry
      - beeja-cloud-gateway
      - beeja-db-1
  beeja-file-management:
    build: ./beeja-file-management
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    ports:
      - "8090:8090"
    depends_on:
      - beeja-service-registry
      - beeja-cloud-gateway
      - beeja-db-1

  beeja-finance:
    build: ./beeja-finance
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    ports:
      - "8092:8092"
    depends_on:
      - beeja-service-registry
      - beeja-cloud-gateway
      - beeja-db-1

  beeja-recruitment:
    build: ./beeja-recruitment
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    ports:
      - "8095:8095"
    depends_on:
      - beeja-service-registry
      - beeja-cloud-gateway
      - beeja-db-1
  beeja-db-1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: beeja-mongodb-replicaset
    image: mongo:latest
    restart: always
    command: [ "--replSet", "rs0", "--bind_ip_all", "--port", "27017", "--keyFile", "/opt/keyfile/mongo-keyfile" ]
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'127.0.0.1:27017'}]}) }" | mongosh --port 27017 -u root -p password --authenticationDatabase admin
      interval: 5s
      timeout: 15s
      start_period: 15s
      retries: 10
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - db-store:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js




volumes:
  db-store:





