server:
  servlet:
    context-path: /files
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  port: 8090
spring:
  output:
    ansi:
      enabled: ALWAYS
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
  application:
    name: file-service

  data:
    mongodb:
      uri: mongodb://root:password@localhost:27017/?replicaSet=rs0&directConnection=true
      database: files_sbox

beeja:
  fileUploadLocation: C:/beeja-file-storage
  #provide localpath

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

client-urls:
  employeeService: http://localhost:8089/employees
  accountsService: http://localhost:8080/accounts
# actuator
management:
  endpoints.web.exposure.include: health,info
  info.env.enabled: true
info:
  application.name: ${spring.application.name}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    url: /openApi.yaml
file-format:
  allowedTypes:
    - application/pdf
    - application/vnd.openxmlformats-officedocument.wordprocessingml.document
    - application/msword
    - image/png
    - image/jpeg
jwt:
  secret: zj1pbrDrd305tzhIhUbCC6TpMaayzG6JlSLsYqOzXwzj1pbrDrd305tzhIhUbCC6TpMaayzG6JlSLsYqOzXwzj1pbrDrd305tzhIhUbCC6TpMaayzG6JlSLsYqOzXw